apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-noticias-configmap
          livenessProbe: #testa se a aplicação está respondendo de acordo com o esperado. Retorno >= 200 && < 400 == Saudável
            httpGet:
              path: /
              port: 80
            periodSeconds: 10 #Testa a cada 10 segundos
            failureThreshold: 3 #Se falhar 3 vezes reinicia o container
            initialDelaySeconds: 20 #Atraso no início dos testes
          readinessProbe: #testa se a aplicação está pronta de acordo com o esperado. Retorno >= 200 && < 400 == Saudável
            httpGet:
              path: /
              port: 80
            periodSeconds: 10 #Testa a cada 10 segundos
            failureThreshold: 3 #Se falhar 3 vezes ignora
            initialDelaySeconds: 20 #Atraso no início dos testes
          resources:
            requests:
              cpu: 10m            
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias #Precisa ser igual ao definido em spec.template.metadata.labels caso contrário não funciona
