apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-noticias-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: sistema-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-noticias-configmap
          livenessProbe: #testa se a aplicação está respondendo de acordo com o esperado. Retorno >= 200 && < 400 == Saudável
            httpGet:
              path: /
              port: 80
            periodSeconds: 10 #Testa a cada 10 segundos
            failureThreshold: 3 #Se falhar 3 vezes reinicia o container
            initialDelaySeconds: 20 #Atraso no início dos testes
          readinessProbe: #testa se a aplicação está pronta de acordo com o esperado. Retorno >= 200 && < 400 == Saudável
            httpGet:
              path: /inserir_noticias.php
              port: 80
            periodSeconds: 10 #Testa a cada 10 segundos
            failureThreshold: 3 #Se falhar 3 vezes ignora
            initialDelaySeconds: 20 #Atraso no início dos testes
  selector:
    matchLabels:
      app: sistema-noticias #Precisa ser igual ao definido em spec.template.metadata.labels caso contrário não funciona
