apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: db-noticias-replica-set
spec:
  replicas: 1
  template:
    metadata:
      name: db-noticias
      labels:
        app: db-noticias
    spec:
      containers:
        - name: db-noticias-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-configmap
  selector:
    matchLabels:
      app: db-noticias #Precisa ser igual ao definido em spec.template.metadata.labels caso contrário não funciona
