apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMount:
        - mountPath: /mnt
          name: primeiro-volume
    - name: jenkins-container
      image: jenkins:alpine
      volumeMount:
        - mountPath: /mnt
          name: primeiro-volume      
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /C/dev/estudo/volumes/primeiro-volume
        type: Directory